# Generated by Django 5.1.7 on 2026-07-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantPromptNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('lang', models.CharField(choices=[('az', 'Azərbaycan'), ('en', 'English'), ('both', 'Both')], default='both', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assistant Prompt Note',
                'verbose_name_plural': 'Assistant Prompt Notes',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssistantPromptSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_prompt_az', models.TextField(blank=True, default='')),
                ('base_prompt_en', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assistant Prompt Settings',
                'verbose_name_plural': 'Assistant Prompt Settings',
            },
        ),
    ]
