# Generated by Django 5.1.7 on 2026-04-23 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(default='🏅', max_length=8)),
                ('color', models.CharField(default='#ff5672', max_length=16)),
                ('criteria', models.CharField(choices=[('first_task', 'Complete first task'), ('first_room', 'Complete first room'), ('room_complete', 'Complete specific room'), ('tasks_count', 'Complete N tasks'), ('xp_threshold', 'Reach XP threshold'), ('exam_pass', 'Pass an exam'), ('streak', 'Maintain streak')], max_length=32)),
                ('criteria_value', models.CharField(blank=True, default='', max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('task_complete', 'Task completed'), ('room_complete', 'Room completed'), ('badge_earned', 'Badge earned'), ('exam_submit', 'Exam submitted'), ('enroll', 'Enrolled'), ('rank_up', 'Rank up')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('xp_delta', models.IntegerField(default=0)),
                ('target_slug', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.PositiveIntegerField(default=0)),
                ('rank', models.CharField(choices=[('recruit', 'Recruit'), ('script_kiddie', 'Script Kiddie'), ('operative', 'Operative'), ('hunter', 'Hunter'), ('specialist', 'Specialist'), ('analyst', 'Analyst'), ('architect', 'Architect'), ('operator', 'Operator'), ('ghost', 'Ghost')], default='recruit', max_length=32)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, default='')),
                ('country', models.CharField(blank=True, default='', max_length=80)),
                ('avatar_hue', models.PositiveIntegerField(default=210)),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('rooms_completed', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-xp', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='accounts.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
