# Generated by Django 5.1.7 on 2026-07-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_activity_kind_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='kind',
            field=models.CharField(choices=[('task_complete', 'Task completed'), ('room_complete', 'Room completed'), ('exam_submit', 'Exam submitted'), ('enroll', 'Enrolled'), ('rank_up', 'Rank up'), ('admin_grant', 'XP awarded by admin')], max_length=32),
        ),
    ]
