# Generated by Django 5.1.7 on 2026-04-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_roomtag_alter_category_options_category_color_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="expected_answer",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="QuestionAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("submitted_answer", models.TextField(blank=True, default="")),
                ("is_correct", models.BooleanField(default=False)),
                ("points_awarded", models.PositiveIntegerField(default=0)),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                ("hint_used", models.BooleanField(default=False)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to="courses.question"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="question_attempts", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-attempted_at", "-id"],
            },
        ),
    ]
