from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_lesson_video_lesson_questions_completion"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS "courses_lessonquestion" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "text" text NOT NULL,
                "explanation" text NOT NULL,
                "at_seconds" integer NULL,
                "points" integer NOT NULL CHECK ("points" >= 0),
                "order" integer NOT NULL CHECK ("order" >= 0),
                "lesson_id" bigint NOT NULL REFERENCES "courses_lesson" ("id") ON DELETE CASCADE
            );
            CREATE TABLE IF NOT EXISTS "courses_lessonquestionchoice" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "text" varchar(400) NOT NULL,
                "is_correct" boolean NOT NULL,
                "order" integer NOT NULL CHECK ("order" >= 0),
                "question_id" bigint NOT NULL REFERENCES "courses_lessonquestion" ("id") ON DELETE CASCADE
            );
            CREATE TABLE IF NOT EXISTS "courses_lessonquestionattempt" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "is_correct" boolean NOT NULL,
                "points_awarded" integer NOT NULL CHECK ("points_awarded" >= 0),
                "attempted_at" timestamptz NOT NULL,
                "question_id" bigint NOT NULL REFERENCES "courses_lessonquestion" ("id") ON DELETE CASCADE,
                "selected_choice_id" bigint REFERENCES "courses_lessonquestionchoice" ("id") ON DELETE SET NULL,
                "user_id" integer NOT NULL REFERENCES "auth_user" ("id") ON DELETE CASCADE,
                UNIQUE ("user_id", "question_id")
            );
            CREATE TABLE IF NOT EXISTS "courses_userlessonprogress" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "is_completed" boolean NOT NULL,
                "completed_at" timestamptz NULL,
                "lesson_id" bigint NOT NULL REFERENCES "courses_lesson" ("id") ON DELETE CASCADE,
                "user_id" integer NOT NULL REFERENCES "auth_user" ("id") ON DELETE CASCADE,
                UNIQUE ("user_id", "lesson_id")
            );
            -- Mission / Exam related tables (created here because some state-only migrations expect them)
            CREATE TABLE IF NOT EXISTS "courses_mission" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "title" varchar(200) NOT NULL,
                "slug" varchar(50) NOT NULL,
                "description" text NOT NULL,
                "short_description" varchar(300) NOT NULL,
                "difficulty" varchar(20) NOT NULL,
                "cover_color" varchar(16) NOT NULL,
                "icon" varchar(8) NOT NULL,
                "estimated_hours" integer NOT NULL,
                "xp_reward" integer NOT NULL,
                "order" integer NOT NULL,
                "is_published" boolean NOT NULL,
                "created_at" timestamptz NOT NULL,
                "updated_at" timestamptz NOT NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS courses_mission_slug_key ON "courses_mission" ("slug");

            CREATE TABLE IF NOT EXISTS "courses_missionpass" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "title" varchar(200) NOT NULL,
                "content" text NOT NULL,
                "order" integer NOT NULL,
                "estimated_minutes" integer NOT NULL,
                "is_published" boolean NOT NULL,
                "mission_id" bigint NOT NULL REFERENCES "courses_mission" ("id") ON DELETE CASCADE
            );
            CREATE UNIQUE INDEX IF NOT EXISTS courses_missionpass_mission_order_key ON "courses_missionpass" ("mission_id", "order");

            CREATE TABLE IF NOT EXISTS "courses_missionexam" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "title" varchar(200) NOT NULL,
                "description" text NOT NULL,
                "passing_score" smallint NOT NULL,
                "time_limit_minutes" smallint NOT NULL,
                "max_attempts" smallint NOT NULL,
                "xp_reward" integer NOT NULL,
                "is_published" boolean NOT NULL,
                "mission_id" bigint NOT NULL REFERENCES "courses_mission" ("id") ON DELETE CASCADE
            );
            CREATE UNIQUE INDEX IF NOT EXISTS courses_missionexam_mission_id_key ON "courses_missionexam" ("mission_id");

            CREATE TABLE IF NOT EXISTS "courses_missionexamquestion" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "question_text" text NOT NULL,
                "question_type" varchar(20) NOT NULL DEFAULT 'closed',
                "order" smallint NOT NULL DEFAULT 0,
                "is_multiple" boolean NOT NULL DEFAULT false,
                "expected_answer" text NOT NULL DEFAULT '',
                "explanation" text NOT NULL DEFAULT '',
                "exam_id" bigint NOT NULL REFERENCES "courses_missionexam" ("id") ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS "courses_missionexamchoice" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "choice_text" varchar(500) NOT NULL,
                "is_correct" boolean NOT NULL,
                "order" smallint NOT NULL,
                "question_id" bigint NOT NULL REFERENCES "courses_missionexamquestion" ("id") ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS "courses_missionexamattempt" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "attempt_number" smallint NOT NULL DEFAULT 1,
                "started_at" timestamptz NOT NULL,
                "submitted_at" timestamptz NULL,
                "score" double precision NULL,
                "passed" boolean NOT NULL DEFAULT false,
                "exam_id" bigint NOT NULL REFERENCES "courses_missionexam" ("id") ON DELETE CASCADE,
                "user_id" integer NOT NULL REFERENCES "auth_user" ("id") ON DELETE CASCADE
            );
            CREATE UNIQUE INDEX IF NOT EXISTS courses_missionexamattempt_user_exam_attempt_key ON "courses_missionexamattempt" ("user_id", "exam_id", "attempt_number");

            CREATE TABLE IF NOT EXISTS "courses_missionexamanswer" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "submitted_answer" text NOT NULL DEFAULT '',
                "attempt_id" bigint NOT NULL REFERENCES "courses_missionexamattempt" ("id") ON DELETE CASCADE,
                "question_id" bigint NOT NULL REFERENCES "courses_missionexamquestion" ("id") ON DELETE CASCADE
            );
            CREATE UNIQUE INDEX IF NOT EXISTS courses_missionexamanswer_attempt_question_key ON "courses_missionexamanswer" ("attempt_id", "question_id");

            CREATE TABLE IF NOT EXISTS "courses_missionexamanswer_selected_choices" (
                "missionexamanswer_id" bigint NOT NULL REFERENCES "courses_missionexamanswer" ("id") ON DELETE CASCADE,
                "missionexamchoice_id" bigint NOT NULL REFERENCES "courses_missionexamchoice" ("id") ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS "courses_missionprogress" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "started_at" timestamptz NOT NULL,
                "completed_at" timestamptz NULL,
                "is_completed" boolean NOT NULL DEFAULT false,
                "exam_passed" boolean NOT NULL DEFAULT false,
                "mission_id" bigint NOT NULL REFERENCES "courses_mission" ("id") ON DELETE CASCADE,
                "user_id" integer NOT NULL REFERENCES "auth_user" ("id") ON DELETE CASCADE
            );
            CREATE UNIQUE INDEX IF NOT EXISTS courses_missionprogress_user_mission_key ON "courses_missionprogress" ("user_id", "mission_id");

            CREATE TABLE IF NOT EXISTS "courses_missionpasscompletion" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "completed_at" timestamptz NOT NULL,
                "mission_pass_id" bigint NOT NULL REFERENCES "courses_missionpass" ("id") ON DELETE CASCADE,
                "user_id" integer NOT NULL REFERENCES "auth_user" ("id") ON DELETE CASCADE
            );
            CREATE UNIQUE INDEX IF NOT EXISTS courses_missionpasscompletion_user_pass_key ON "courses_missionpasscompletion" ("user_id", "mission_pass_id");
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
