from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_remove_exam_models"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS "courses_missionexam" (
                        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        "title" varchar(200) NOT NULL,
                        "description" text NOT NULL,
                        "passing_score" smallint NOT NULL,
                        "time_limit_minutes" smallint NOT NULL,
                        "max_attempts" smallint NOT NULL,
                        "xp_reward" integer NOT NULL,
                        "is_published" boolean NOT NULL,
                        "mission_id" bigint NOT NULL REFERENCES "courses_mission" ("id") ON DELETE CASCADE
                    );
                    CREATE TABLE IF NOT EXISTS "courses_missionexamquestion" (
                        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        "question_text" text NOT NULL,
                        "order" smallint NOT NULL DEFAULT 0,
                        "is_multiple" boolean NOT NULL DEFAULT false,
                        "explanation" text NOT NULL DEFAULT '',
                        "exam_id" bigint NOT NULL REFERENCES "courses_missionexam" ("id") ON DELETE CASCADE
                    );
                    ALTER TABLE "courses_missionexamquestion"
                        ADD COLUMN IF NOT EXISTS "question_type" varchar(20) NOT NULL DEFAULT 'closed';
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[],
        ),
    ]
