# Generated by Django 5.1.7 on 2026-07-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_room_env'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionattempt',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionchoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionattempt',
            name='user',
        ),
        migrations.AlterField(
            model_name='room',
            name='env',
            field=models.CharField(blank=True, choices=[('docker', 'Docker'), ('vm', 'Virtual Machine'), ('linux', 'Linux'), ('windows', 'Windows'), ('web', 'Web App'), ('cloud', 'Cloud')], default='docker', help_text='Type of isolated environment (Docker, VM, Web App…).', max_length=20, verbose_name='Lab Environment'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionChoice',
        ),
        migrations.DeleteModel(
            name='QuestionAttempt',
        ),
    ]
